/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class si_fct_unl_Warehouse */

#ifndef _Included_si_fct_unl_Warehouse
#define _Included_si_fct_unl_Warehouse
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     si_fct_unl_Warehouse
 * Method:    initializeHardwarePorts
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_si_fct_unl_Warehouse_initializeHardwarePorts
  (JNIEnv *, jobject);

/*
 * Class:     si_fct_unl_Warehouse
 * Method:    randomPosition
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_si_fct_unl_Warehouse_randomPosition
  (JNIEnv *, jobject);

/*
 * Class:     si_fct_unl_Warehouse
 * Method:    stopAll
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_si_fct_unl_Warehouse_stopAll
  (JNIEnv *, jobject);

/*
 * Class:     si_fct_unl_Warehouse
 * Method:    moveXRight
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_si_fct_unl_Warehouse_moveXRight
  (JNIEnv *, jobject);

/*
 * Class:     si_fct_unl_Warehouse
 * Method:    moveXLeft
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_si_fct_unl_Warehouse_moveXLeft
  (JNIEnv *, jobject);

/*
 * Class:     si_fct_unl_Warehouse
 * Method:    stopXRight
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_si_fct_unl_Warehouse_stopXRight
  (JNIEnv *, jobject);

/*
 * Class:     si_fct_unl_Warehouse
 * Method:    stopXLeft
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_si_fct_unl_Warehouse_stopXLeft
  (JNIEnv *, jobject);

/*
 * Class:     si_fct_unl_Warehouse
 * Method:    stopX
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_si_fct_unl_Warehouse_stopX
  (JNIEnv *, jobject);

/*
 * Class:     si_fct_unl_Warehouse
 * Method:    getXPosition
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_si_fct_unl_Warehouse_getXPosition
  (JNIEnv *, jobject);

/*
 * Class:     si_fct_unl_Warehouse
 * Method:    gotoX
 * Signature: (I)V
 */
//JNIEXPORT void JNICALL Java_si_fct_unl_Warehouse_gotoX
//  (JNIEnv *, jobject, jint);

/*
 * Class:     si_fct_unl_Warehouse
 * Method:    moveYIn
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_si_fct_unl_Warehouse_moveYIn
  (JNIEnv *, jobject);

/*
 * Class:     si_fct_unl_Warehouse
 * Method:    moveYOut
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_si_fct_unl_Warehouse_moveYOut
  (JNIEnv *, jobject);

/*
 * Class:     si_fct_unl_Warehouse
 * Method:    StopYIn
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_si_fct_unl_Warehouse_StopYIn
  (JNIEnv *, jobject);

/*
 * Class:     si_fct_unl_Warehouse
 * Method:    StopYOut
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_si_fct_unl_Warehouse_StopYOut
  (JNIEnv *, jobject);

/*
 * Class:     si_fct_unl_Warehouse
 * Method:    stopY
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_si_fct_unl_Warehouse_stopY
  (JNIEnv *, jobject);

/*
 * Class:     si_fct_unl_Warehouse
 * Method:    getYPosition
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_si_fct_unl_Warehouse_getYPosition
  (JNIEnv *, jobject);

/*
 * Class:     si_fct_unl_Warehouse
 * Method:    gotoY
 * Signature: (I)V
 */
//JNIEXPORT void JNICALL Java_si_fct_unl_Warehouse_gotoY
//  (JNIEnv *, jobject, jint);

/*
 * Class:     si_fct_unl_Warehouse
 * Method:    moveZUp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_si_fct_unl_Warehouse_moveZUp
  (JNIEnv *, jobject);

/*
 * Class:     si_fct_unl_Warehouse
 * Method:    moveZDown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_si_fct_unl_Warehouse_moveZDown
  (JNIEnv *, jobject);

/*
 * Class:     si_fct_unl_Warehouse
 * Method:    StopZUp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_si_fct_unl_Warehouse_StopZUp
  (JNIEnv *, jobject);

/*
 * Class:     si_fct_unl_Warehouse
 * Method:    StopZDown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_si_fct_unl_Warehouse_StopZDown
  (JNIEnv *, jobject);

/*
 * Class:     si_fct_unl_Warehouse
 * Method:    stopZ
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_si_fct_unl_Warehouse_stopZ
  (JNIEnv *, jobject);

/*
 * Class:     si_fct_unl_Warehouse
 * Method:    getZPosition
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_si_fct_unl_Warehouse_getZPosition
  (JNIEnv *, jobject);

/*
 * Class:     si_fct_unl_Warehouse
 * Method:    gotoZ
 * Signature: (I)V
 */
//JNIEXPORT void JNICALL Java_si_fct_unl_Warehouse_gotoZ
//  (JNIEnv *, jobject, jint);

/*
 * Class:     si_fct_unl_Warehouse
 * Method:    getXMoving
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_si_fct_unl_Warehouse_getXMoving
  (JNIEnv *, jobject);

/*
 * Class:     si_fct_unl_Warehouse
 * Method:    getYMoving
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_si_fct_unl_Warehouse_getYMoving
  (JNIEnv *, jobject);

/*
 * Class:     si_fct_unl_Warehouse
 * Method:    getZMoving
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_si_fct_unl_Warehouse_getZMoving
  (JNIEnv *, jobject);

/*
 * Class:     si_fct_unl_Warehouse
 * Method:    getLeftStationMoving
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_si_fct_unl_Warehouse_getLeftStationMoving
  (JNIEnv *, jobject);

/*
 * Class:     si_fct_unl_Warehouse
 * Method:    getRightStationMoving
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_si_fct_unl_Warehouse_getRightStationMoving
  (JNIEnv *, jobject);

/*
 * Class:     si_fct_unl_Warehouse
 * Method:    isAtZUp
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_si_fct_unl_Warehouse_isAtZUp
  (JNIEnv *, jobject);

/*
 * Class:     si_fct_unl_Warehouse
 * Method:    isAtZDown
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_si_fct_unl_Warehouse_isAtZDown
  (JNIEnv *, jobject);

/*
 * Class:     si_fct_unl_Warehouse
 * Method:    isPartInCage
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_si_fct_unl_Warehouse_isPartInCage
  (JNIEnv *, jobject);

/*
 * Class:     si_fct_unl_Warehouse
 * Method:    isPartOnLeftStation
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_si_fct_unl_Warehouse_isPartOnLeftStation
  (JNIEnv *, jobject);

/*
 * Class:     si_fct_unl_Warehouse
 * Method:    isPartOnRightStation
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_si_fct_unl_Warehouse_isPartOnRightStation
  (JNIEnv *, jobject);

/*
 * Class:     si_fct_unl_Warehouse
 * Method:    moveLeftStationInside
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_si_fct_unl_Warehouse_moveLeftStationInside
  (JNIEnv *, jobject);

/*
 * Class:     si_fct_unl_Warehouse
 * Method:    moveLeftStationOutside
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_si_fct_unl_Warehouse_moveLeftStationOutside
  (JNIEnv *, jobject);

/*
 * Class:     si_fct_unl_Warehouse
 * Method:    stopLeftLtation
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_si_fct_unl_Warehouse_stopLeftLtation
  (JNIEnv *, jobject);

/*
 * Class:     si_fct_unl_Warehouse
 * Method:    moveRightStationInside
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_si_fct_unl_Warehouse_moveRightStationInside
  (JNIEnv *, jobject);

/*
 * Class:     si_fct_unl_Warehouse
 * Method:    moveRightStationOutside
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_si_fct_unl_Warehouse_moveRightStationOutside
  (JNIEnv *, jobject);

/*
 * Class:     si_fct_unl_Warehouse
 * Method:    stopRightStation
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_si_fct_unl_Warehouse_stopRightStation
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
